deploymentName: gateway-deployment
deploymentLabel: gateway
replicaCount: 1

image:
  repository: codebuddyapp/gateway
  tag: latest

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

profile_enabled: false
eureka_enabled: true